container-engine = "podman"

build-frontend = "uv"
enable = ["pypy"]
build = [
    "cp310-*", # Python 3.10  
    "cp311-*", # Python 3.11  
    "cp312-*", # Python 3.12  
    "cp313-*", # Python 3.13  
    "cp314-*", # Python 3.14  
    "pp311-*", # PyPy 3.11  
]
skip = [
    "*t-*", # Free-threading
    "*-musllinux_s390x",
]
test-command = "pytest"
test-groups = ["pytest"] # uv pip install --group test  

[linux]
archs = [
    "x86_64",
    "i686",
    "aarch64",
    "armv7l",
    "ppc64le",
    "s390x",
    "riscv64",
]
test-skip = "*-manylinux_{aarch64,armv7l} *-musllinux_{i686,aarch64,armv7l}"
manylinux-x86_64-image = "quay.io/pypa/manylinux2014_x86_64:2026.03.01-1"
manylinux-i686-image = "quay.io/pypa/manylinux2014_i686:2026.03.01-1"
manylinux-aarch64-image = "quay.io/pypa/manylinux_2_39_aarch64:2026.03.01-1"
manylinux-armv7l-image = "quay.io/pypa/manylinux_2_31_armv7l:2026.03.01-1"
manylinux-ppc64le-image = "quay.io/pypa/manylinux2014_ppc64le:2026.03.01-1"
manylinux-s390x-image = "quay.io/pypa/manylinux2014_s390x:2026.03.01-1"
manylinux-riscv64-image = "quay.io/pypa/manylinux_2_39_riscv64:2026.03.01-1"
musllinux-x86_64-image = "quay.io/pypa/musllinux_1_2_x86_64:2026.03.01-1"
musllinux-i686-image = "quay.io/pypa/musllinux_1_2_i686:2026.03.01-1"
musllinux-aarch64-image = "quay.io/pypa/musllinux_1_2_aarch64:2026.03.01-1"
musllinux-armv7l-image = "quay.io/pypa/musllinux_1_2_armv7l:2026.03.01-1"
musllinux-ppc64le-image = "quay.io/pypa/musllinux_1_2_ppc64le:2026.03.01-1"
musllinux-riscv64-image = "quay.io/pypa/musllinux_1_2_riscv64:2026.03.01-1"

[macos]
archs = [
    "x86_64",
    "arm64",
    "universal2",
]
test-skip = "*-macosx_arm64"

[windows]
archs = [
    "AMD64",
    "x86",
]

[[overrides]]
select = "*"
before-build = [
    "python scripts/prepare_hpy_source.py",
]

[[overrides]]
select = "cp3{13,14}-*"
test-environment = { PYTHONMALLOC = "mimalloc" }
