[tool.cibuildwheel]
container-engine = "podman"
build-frontend = "uv"
enable = ["pypy"]
build = [
    "cp310-*", # Python 3.10
    "cp311-*", # Python 3.11
    "cp312-*", # Python 3.12
    "cp313-*", # Python 3.13
    "cp314-*", # Python 3.14
    "pp311-*", # PyPy 3.11
]
skip = [
    "*t-*", # Free-threading
]
test-command = "pytest {project}/tests"
test-groups = ["pytest"] # uv pip install --group test

environment = { SETUPTOOLS_SCM_PRETEND_VERSION = "0.0.0" }

[tool.cibuildwheel.linux]
archs = [
    "x86_64",
    "i686",
    "aarch64",
    "ppc64le",
    "s390x",
    "armv7l",
    "riscv64",
]

manylinux-x86_64-image = "manylinux_2_28"
manylinux-i686-image = "manylinux_2_28"
manylinux-aarch64-image = "manylinux_2_28"
manylinux-armv7l-image = "manylinux_2_31"
manylinux-ppc64le-image = "manylinux_2_28"
manylinux-s390x-image = "manylinux_2_28"
manylinux-riscv64-image = "manylinux_2_39"

musllinux-x86_64-image = "musllinux_1_2"
musllinux-i686-image = "musllinux_1_2"
musllinux-aarch64-image = "musllinux_1_2"
musllinux-armv7l-image = "musllinux_1_2"
musllinux-ppc64le-image = "musllinux_1_2"
musllinux-s390x-image = "musllinux_1_2"
musllinux-riscv64-image = "musllinux_1_2"

[tool.cibuildwheel.macos]
archs = [
    "x86_64",
    "arm64",
    "universal2",
]

[tool.cibuildwheel.windows]
archs = [
    "AMD64",
    "x86",
    "ARM64",
]

[[tool.cibuildwheel.overrides]]
select = "cp3{13,14}-*"
test-environment = { PYTHONMALLOC = "mimalloc" }

[[tool.cibuildwheel.overrides]]
# uv is not available in these images
build-frontend = "build"
select = "*-musllinux_{ppc64le,s390x,riscv64}"

[[tool.cibuildwheel.overrides]]
# See: https://codeberg.org/ziglang/zig/issues/31865#issuecomment-13204506
select = "*-win_arm64"
environment = { CI_WIN_ARM_64_ZIG_ENV = ".zig-sdk/zig-x86_64-windows-0.16.0/zig.exe" }
before-all = [
    "mkdir .zig-sdk",
    "curl.exe -fsSLo .zig-sdk/zig.zip https://ziglang.org/download/0.16.0/zig-x86_64-windows-0.16.0.zip",
    "tar -xf .zig-sdk/zig.zip -C .zig-sdk",
]
