from typing import Any

class _UUID:
    @property
    def bytes(self) -> bytes: ...

    @property
    def bytes_le(self) -> bytes: ...

    @property
    def clock_seq(self) -> int: ...

    @property
    def clock_seq_hi_variant(self) -> int: ...

    @property
    def clock_seq_low(self) -> int: ...

    @property
    def fields(self) -> tuple[int, int, int, int, int, int]: ...

    @property
    def hex(self) -> str: ...

    @property
    def int(self) -> int: ...

    @property
    def node(self) -> int: ...

    @property
    def time(self) -> int: ...

    @property
    def time_hi_version(self) -> int: ...

    @property
    def time_low(self) -> int: ...

    @property
    def time_mid(self) -> int: ...

    @property
    def timestamp(self) -> int: ...

    @property
    def urn(self) -> str: ...

    def __copy__(self) -> _UUID: ...
    def __deepcopy__(self, memo: dict[Any, Any], /) -> _UUID: ...
    def __hash__(self) -> int: ...
    def __int__(self) -> int: ...
    def __lt__(self, other: Any, /) -> bool: ...
    def __le__(self, other: Any, /) -> bool: ...
    def __eq__(self, other: Any, /) -> bool: ...
    def __ne__(self, other: Any, /) -> bool: ...
    def __gt__(self, other: Any, /) -> bool: ...
    def __ge__(self, other: Any, /) -> bool: ...

def _uuid7(timestamp: int | None = None, nanos: int | None = None) -> _UUID: ...

def _reseed_rng() -> None: ...
