import typing

class UUID:
    @property
    def hex(self) -> str: ...

    @property
    def int(self) -> int: ...

    @property
    def timestamp(self) -> int: ...

    @property
    def version(self) -> int: ...

    def __hash__(self) -> int: ...
    def __lt__(self, other: typing.Any, /) -> bool: ...
    def __le__(self, other: typing.Any, /) -> bool: ...
    def __eq__(self, other: typing.Any, /) -> bool: ...
    def __ne__(self, other: typing.Any, /) -> bool: ...
    def __gt__(self, other: typing.Any, /) -> bool: ...
    def __ge__(self, other: typing.Any, /) -> bool: ...

def _uuid7(timestamp: int | None = None, nanos: int | None = None) -> UUID: ...

def _reseed_rng() -> None: ...
