# This file auto generated by `setuptools-scm`!
# DO NOT EDIT MANUALLY !!!

version: str = "0.1.dev0+d20260322"
__version__: str = version

commit_hash: str = "None"
version_timestamp: str = "2026-03-22 23:11:34.782448+00:00"

tag: str = "0.0"
branch: str = "master"
commit_date: str = "2026-03-22"
commit_count_since_tag: int = 0
