#include "random.h"

#include "platform.h"

/*
 * PCG Random Number Generation for C.
 *
 * Copyright 2014-2019 Melissa O'Neill <oneill@pcg-random.org>,
 *                     and the PCG Project contributors.
 *
 * SPDX-License-Identifier: (Apache-2.0 OR MIT)
 *
 * Licensed under the Apache License, Version 2.0 (provided in
 * LICENSE-APACHE.txt and at http://www.apache.org/licenses/LICENSE-2.0)
 * or under the MIT license (provided in LICENSE-MIT.txt and at
 * http://opensource.org/licenses/MIT), at your option. This file may not
 * be copied, modified, or distributed except according to those terms.
 *
 * Distributed on an "AS IS" BASIS, WITHOUT WARRANTY OF ANY KIND, either
 * express or implied.  See your chosen license for details.
 *
 * For additional information about the PCG random number generation scheme,
 * visit http://www.pcg-random.org/.
 */

/*
 * This code is derived from the canonical C++ PCG implementation, which
 * has many additional features and is preferable if you can use C++ in
 * your project.
 *
 * Much of the derivation was performed mechanically.  In particular, the
 * output functions were generated by compiling the C++ output functions
 * into LLVM bitcode and then transforming that using the LLVM C backend
 * (from https://github.com/draperlaboratory/llvm-cbe), and then
 * postprocessing and hand editing the output.
 *
 * Much of the remaining code was generated by C-preprocessor metaprogramming.
 */

#define PCG_DEFAULT_MULTIPLIER_64 6364136223846793005ULL
#define PCG_DEFAULT_INCREMENT_64 1442695040888963407ULL
#define PCG_OUTPUT_MULTIPLIER_64 12605985483714917081ULL

#define UUID_RAND_MASK 0x3FFFFFFFFFFFFFFFULL
#define RESEED_MASK ((1ULL << 41) - 1ULL)
#define LOW30_MASK ((1ULL << 30) - 1ULL)

typedef struct {
    uint64_t state;
} pcg64si_random_t;

static pcg64si_random_t pcg64si_global = {0};
static int pcg64si_seeded = 0;

static uint64_t unpack_u64_be(const unsigned char bytes[8]) {
    return (uint64_t)bytes[0] << 56 | (uint64_t)bytes[1] << 48 | (uint64_t)bytes[2] << 40 |
           (uint64_t)bytes[3] << 32 | (uint64_t)bytes[4] << 24 | (uint64_t)bytes[5] << 16 |
           (uint64_t)bytes[6] << 8 | (uint64_t)bytes[7];
}

/* Output functions.  These are the core of the PCG generation scheme. */
static uint64_t pcg_output_rxs_m_xs_64_64(const uint64_t state) {
    const uint64_t word = (state >> ((state >> 59u) + 5u) ^ state) * PCG_OUTPUT_MULTIPLIER_64;
    return word >> 43u ^ word;
}

static void pcg_oneseq_64_step_r(pcg64si_random_t *rng) {
    rng->state = rng->state * PCG_DEFAULT_MULTIPLIER_64 + PCG_DEFAULT_INCREMENT_64;
}

static void pcg_oneseq_64_srandom_r(pcg64si_random_t *rng, const uint64_t initstate) {
    rng->state = 0U;
    pcg_oneseq_64_step_r(rng);
    rng->state += initstate;
    pcg_oneseq_64_step_r(rng);
}

static uint64_t pcg_oneseq_64_rxs_m_xs_64_random_r(pcg64si_random_t *rng) {
    const uint64_t oldstate = rng->state;

    pcg_oneseq_64_step_r(rng);
    return pcg_output_rxs_m_xs_64_64(oldstate);
}

static int rnd_u64_secure(uint64_t *out) {
    unsigned char bytes[8];

    if (fill_random(bytes, sizeof(bytes)) != 0) {
        PyErr_SetString(PyExc_OSError, "unable to generate random bytes");
        return -1;
    }

    *out = unpack_u64_be(bytes);
    return 0;
}

static uint64_t next_u64(void) {
    return pcg_oneseq_64_rxs_m_xs_64_random_r(&pcg64si_global);
}

int random_ensure_seeded(void) {
    unsigned char seed[16];
    uint64_t left = 0;
    uint64_t right = 0;
    uint64_t initstate = 0;

    if (pcg64si_seeded) {
        return 0;
    }

    if (fill_random(seed, sizeof(seed)) != 0) {
        PyErr_SetString(PyExc_OSError, "unable to seed UUIDv7 generator");
        return -1;
    }

    memcpy(&left, seed, sizeof(left));
    memcpy(&right, seed + sizeof(left), sizeof(right));
    initstate = left ^ pcg_output_rxs_m_xs_64_64(right);
    pcg_oneseq_64_srandom_r(&pcg64si_global, initstate);

#ifdef _WIN32
    platform_seeded();
#endif
    pcg64si_seeded = 1;
    return 0;
}

void random_reseed(void) {
    pcg64si_seeded = 0;
}

uint64_t random_counter42(void) {
    return next_u64() & RESEED_MASK;
}

int random_counter42_secure(uint64_t *counter) {
    uint64_t random64 = 0;

    if (rnd_u64_secure(&random64) != 0) {
        return -1;
    }

    *counter = random64 & RESEED_MASK;
    return 0;
}

void random_split_counter42(const uint64_t counter,
                            const uint32_t low32,
                            uint16_t *rand_a,
                            uint64_t *tail62) {
    *rand_a = (uint16_t)(counter >> 30);
    *tail62 = (counter & LOW30_MASK) << 32 | (uint64_t)low32;
}

void random_next_low32_and_increment(uint32_t *low32, uint64_t *increment) {
    const uint64_t random64 = next_u64();

    *low32 = (uint32_t)random64;
    *increment = 1U + (random64 >> 32 & 0x0FU);
}

int random_next_low32_and_increment_secure(uint32_t *low32, uint64_t *increment) {
    uint64_t random64 = 0;

    if (rnd_u64_secure(&random64) != 0) {
        return -1;
    }

    *low32 = (uint32_t)random64;
    *increment = 1U + (random64 >> 32 & 0x0FU);
    return 0;
}

void random_payload(uint16_t *rand_a, uint64_t *tail62) {
    random_split_counter42(random_counter42(), (uint32_t)next_u64(), rand_a, tail62);
}

int random_payload_secure(uint16_t *rand_a, uint64_t *tail62) {
    uint64_t counter = 0;
    uint64_t random64 = 0;

    if (random_counter42_secure(&counter) != 0) {
        return -1;
    }
    if (rnd_u64_secure(&random64) != 0) {
        return -1;
    }

    random_split_counter42(counter, (uint32_t)random64, rand_a, tail62);
    return 0;
}

uint64_t random_tail62(void) {
    return next_u64() & UUID_RAND_MASK;
}

int random_tail62_secure(uint64_t *tail62) {
    if (rnd_u64_secure(tail62) != 0) {
        return -1;
    }

    *tail62 &= UUID_RAND_MASK;
    return 0;
}
