name: "windows"

on:
  workflow_call:

jobs:
  windows:
    name: "${{ matrix.platform.runner }} / ${{ matrix.platform.target }}"
    runs-on: ${{ matrix.platform.runner }}
    timeout-minutes: 60
    strategy:
      matrix:
        platform:
          - {
            target: AMD64,
            python_arch: x64,
            runner: windows-latest,
          }
          - {
            runner: windows-latest,
            target: x86,
            python_arch: x86,
          }
          - {
            target: ARM64,
            python_arch: arm64,
            runner: windows-11-arm,
          }
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - uses: pypa/cibuildwheel@8d2b08b68458a16aeb24b64e68a09ab1c8e82084 # v3.4.1
        with:
          extras: uv
        env:
          CIBW_ARCHS_WINDOWS: ${{ matrix.platform.target }}

      - name: "Upload wheels"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: wheels-windows-${{ matrix.platform.target }}
          path: wheelhouse/*.whl
